"""Seed a realistic set of Indian hospitals across major cities.

Invoked on backend startup. Idempotent — upserts by hospital id.

All data is realistic-but-representative. Real production data will come from
verified hospital partners + ABDM Health Facility Registry (HFR).
"""
from __future__ import annotations

import logging
from datetime import date

from app.core.db import get_db

logger = logging.getLogger(__name__)

TODAY = date.today().isoformat()


def _price(procedure: str, low: int, typical: int, high: int, notes: str = "") -> dict:
    return {
        "procedure": procedure,
        "low_inr": low,
        "typical_inr": typical,
        "high_inr": high,
        "notes": notes,
    }


def _base_pricing_private() -> list[dict]:
    return [
        _price("OPD Consultation (Specialist)", 700, 1200, 2200),
        _price("Complete Blood Count (CBC)", 300, 450, 700),
        _price("Ultrasound Abdomen", 1500, 2200, 3800),
        _price("MRI Brain (plain)", 6500, 9500, 14500),
        _price("CT Scan Chest", 4500, 6500, 9800),
        _price("Appendectomy (Laparoscopic)", 65000, 95000, 145000),
        _price("Coronary Angiography", 15000, 22000, 38000),
        _price("Cataract Surgery (Phaco, single eye)", 22000, 38000, 65000),
        _price("C-Section Delivery", 55000, 85000, 135000),
        _price("Normal Delivery", 25000, 40000, 65000),
        _price("General Ward per day", 3500, 5500, 9000),
        _price("ICU per day", 15000, 22000, 35000),
    ]


def _base_pricing_govt() -> list[dict]:
    return [
        _price("OPD Consultation (Specialist)", 10, 30, 100),
        _price("Complete Blood Count (CBC)", 30, 60, 120),
        _price("Ultrasound Abdomen", 200, 400, 800),
        _price("MRI Brain (plain)", 2500, 3500, 5000),
        _price("CT Scan Chest", 800, 1500, 2500),
        _price("Appendectomy (Laparoscopic)", 5000, 12000, 25000),
        _price("Coronary Angiography", 2500, 4500, 8000),
        _price("Cataract Surgery (Phaco, single eye)", 800, 2500, 6000),
        _price("C-Section Delivery", 2000, 6000, 15000),
        _price("Normal Delivery", 500, 2000, 5000),
        _price("General Ward per day", 50, 200, 500),
        _price("ICU per day", 1500, 3000, 5000),
    ]


def _base_pricing_premium() -> list[dict]:
    return [
        _price("OPD Consultation (Specialist)", 1500, 2500, 4500),
        _price("Complete Blood Count (CBC)", 600, 900, 1400),
        _price("Ultrasound Abdomen", 3000, 4500, 6800),
        _price("MRI Brain (plain)", 12000, 18000, 26000),
        _price("CT Scan Chest", 8500, 12000, 18000),
        _price("Appendectomy (Laparoscopic)", 145000, 210000, 320000),
        _price("Coronary Angiography", 32000, 48000, 78000),
        _price("Cataract Surgery (Phaco, single eye)", 55000, 85000, 145000),
        _price("C-Section Delivery", 145000, 210000, 320000),
        _price("Normal Delivery", 80000, 125000, 185000),
        _price("General Ward per day", 12000, 18000, 28000),
        _price("ICU per day", 32000, 48000, 75000),
    ]


def _value_score(price: int, quality: int, availability: int, trust: int) -> dict:
    overall = round(
        price * 0.35 + quality * 0.40 + availability * 0.15 + trust * 0.10
    )
    return {
        "overall": overall,
        "price": price,
        "quality": quality,
        "availability": availability,
        "trust": trust,
    }


def _beds(total: int, icu: int, free_gen_pct: float, free_icu_pct: float) -> dict:
    return {
        "total_beds": total,
        "icu_beds": icu,
        "free_general_beds": int((total - icu) * free_gen_pct),
        "free_icu_beds": max(0, int(icu * free_icu_pct)),
        "last_updated": TODAY,
    }


HOSPITALS: list[dict] = [
    # DELHI NCR ----------------------------------------------------------------
    {
        "id": "aiims-delhi",
        "name": "AIIMS Delhi",
        "city": "Delhi",
        "address": "Ansari Nagar East, Sri Aurobindo Marg, New Delhi 110029",
        "tier": "government",
        "specialties": [
            "Cardiology", "Neurology", "Oncology", "Nephrology",
            "Orthopedics", "Trauma", "Pediatrics",
        ],
        "accreditation": ["NABH", "Autonomous Institute of National Importance"],
        "rating": 4.7,
        "review_count": 12480,
        "latitude": 28.5672,
        "longitude": 77.2100,
        "phone": "+91-11-26588500",
        "emergency_247": True,
        "value_score": _value_score(98, 96, 55, 92),
        "beds": _beds(total=2500, icu=280, free_gen_pct=0.12, free_icu_pct=0.10),
        "pricing": _base_pricing_govt(),
        "photo_url": None,
        "established_year": 1956,
        "description": "India\u2019s premier public tertiary care and research institute.",
    },
    {
        "id": "apollo-delhi",
        "name": "Indraprastha Apollo Hospital",
        "city": "Delhi",
        "address": "Sarita Vihar, Delhi-Mathura Road, New Delhi 110076",
        "tier": "premium",
        "specialties": [
            "Cardiology", "Oncology", "Neurosurgery", "Orthopedics",
            "Liver Transplant", "Robotic Surgery",
        ],
        "accreditation": ["NABH", "JCI"],
        "rating": 4.4,
        "review_count": 6420,
        "latitude": 28.5416,
        "longitude": 77.2843,
        "phone": "+91-11-71791090",
        "emergency_247": True,
        "value_score": _value_score(58, 92, 78, 88),
        "beds": _beds(total=710, icu=140, free_gen_pct=0.28, free_icu_pct=0.18),
        "pricing": _base_pricing_premium(),
        "photo_url": None,
        "established_year": 1996,
        "description": "Flagship Apollo hospital \u2014 tertiary care, transplants, robotics.",
    },
    {
        "id": "fortis-shalimar-delhi",
        "name": "Fortis Shalimar Bagh",
        "city": "Delhi",
        "address": "A Block, Shalimar Bagh, New Delhi 110088",
        "tier": "private",
        "specialties": [
            "Cardiology", "Orthopedics", "Neurology", "Gastroenterology",
            "Obstetrics",
        ],
        "accreditation": ["NABH", "NABL"],
        "rating": 4.2,
        "review_count": 3210,
        "latitude": 28.7086,
        "longitude": 77.1650,
        "phone": "+91-11-47134713",
        "emergency_247": True,
        "value_score": _value_score(72, 85, 74, 82),
        "beds": _beds(total=280, icu=60, free_gen_pct=0.24, free_icu_pct=0.20),
        "pricing": _base_pricing_private(),
        "photo_url": None,
        "established_year": 2011,
        "description": "North Delhi multispecialty hospital.",
    },
    {
        "id": "max-saket",
        "name": "Max Super Speciality Hospital, Saket",
        "city": "Delhi",
        "address": "1 Press Enclave Road, Saket, New Delhi 110017",
        "tier": "premium",
        "specialties": [
            "Cardiac Sciences", "Oncology", "Neurosciences", "Renal Sciences",
            "Liver Transplant",
        ],
        "accreditation": ["NABH", "JCI"],
        "rating": 4.3,
        "review_count": 4890,
        "latitude": 28.5285,
        "longitude": 77.2196,
        "phone": "+91-11-26515050",
        "emergency_247": True,
        "value_score": _value_score(60, 90, 76, 86),
        "beds": _beds(total=530, icu=110, free_gen_pct=0.22, free_icu_pct=0.16),
        "pricing": _base_pricing_premium(),
        "photo_url": None,
        "established_year": 2006,
        "description": "South Delhi flagship for cardiac, oncology and transplants.",
    },
    {
        "id": "safdarjung-delhi",
        "name": "VMMC & Safdarjung Hospital",
        "city": "Delhi",
        "address": "Ring Road, Ansari Nagar, New Delhi 110029",
        "tier": "government",
        "specialties": [
            "General Medicine", "Trauma", "Obstetrics", "Pediatrics", "Orthopedics",
        ],
        "accreditation": ["NABH (Entry)"],
        "rating": 4.1,
        "review_count": 7860,
        "latitude": 28.5687,
        "longitude": 77.2085,
        "phone": "+91-11-26707444",
        "emergency_247": True,
        "value_score": _value_score(96, 82, 42, 84),
        "beds": _beds(total=2700, icu=180, free_gen_pct=0.10, free_icu_pct=0.08),
        "pricing": _base_pricing_govt(),
        "photo_url": None,
        "established_year": 1942,
        "description": "Large central government hospital with round-the-clock trauma.",
    },
    # MUMBAI ------------------------------------------------------------------
    {
        "id": "kokilaben-mumbai",
        "name": "Kokilaben Dhirubhai Ambani Hospital",
        "city": "Mumbai",
        "address": "Rao Saheb Achutrao Patwardhan Marg, Andheri West, Mumbai 400053",
        "tier": "premium",
        "specialties": [
            "Cardiac Sciences", "Oncology", "Neurosciences", "Organ Transplant",
            "Robotic Surgery",
        ],
        "accreditation": ["NABH", "JCI"],
        "rating": 4.5,
        "review_count": 5320,
        "latitude": 19.1310,
        "longitude": 72.8281,
        "phone": "+91-22-42696969",
        "emergency_247": True,
        "value_score": _value_score(55, 94, 80, 90),
        "beds": _beds(total=750, icu=140, free_gen_pct=0.20, free_icu_pct=0.14),
        "pricing": _base_pricing_premium(),
        "photo_url": None,
        "established_year": 2009,
        "description": "Reliance-founded quaternary care hospital in Andheri.",
    },
    {
        "id": "lilavati-mumbai",
        "name": "Lilavati Hospital & Research Centre",
        "city": "Mumbai",
        "address": "A-791, Bandra Reclamation, Bandra West, Mumbai 400050",
        "tier": "premium",
        "specialties": [
            "Cardiology", "Orthopedics", "Neurology", "Nephrology", "Oncology",
        ],
        "accreditation": ["NABH", "NABL"],
        "rating": 4.3,
        "review_count": 4180,
        "latitude": 19.0509,
        "longitude": 72.8281,
        "phone": "+91-22-26567777",
        "emergency_247": True,
        "value_score": _value_score(58, 90, 72, 88),
        "beds": _beds(total=340, icu=68, free_gen_pct=0.18, free_icu_pct=0.14),
        "pricing": _base_pricing_premium(),
        "photo_url": None,
        "established_year": 1997,
        "description": "Bandra flagship, trust-run premium tertiary care.",
    },
    {
        "id": "hinduja-mumbai",
        "name": "P. D. Hinduja Hospital",
        "city": "Mumbai",
        "address": "Veer Savarkar Marg, Mahim, Mumbai 400016",
        "tier": "private",
        "specialties": [
            "Nephrology", "Cardiology", "Oncology", "Orthopedics", "Neurology",
        ],
        "accreditation": ["NABH", "NABL"],
        "rating": 4.4,
        "review_count": 3620,
        "latitude": 19.0399,
        "longitude": 72.8409,
        "phone": "+91-22-24447000",
        "emergency_247": True,
        "value_score": _value_score(70, 90, 68, 88),
        "beds": _beds(total=380, icu=64, free_gen_pct=0.22, free_icu_pct=0.16),
        "pricing": _base_pricing_private(),
        "photo_url": None,
        "established_year": 1951,
        "description": "Mahim tertiary care, known for kidney transplant program.",
    },
    {
        "id": "kem-mumbai",
        "name": "KEM Hospital",
        "city": "Mumbai",
        "address": "Acharya Donde Marg, Parel East, Mumbai 400012",
        "tier": "government",
        "specialties": [
            "General Surgery", "Trauma", "Cardiology", "Obstetrics", "Pediatrics",
        ],
        "accreditation": ["NABH (Entry)"],
        "rating": 4.0,
        "review_count": 5620,
        "latitude": 19.0022,
        "longitude": 72.8399,
        "phone": "+91-22-24107000",
        "emergency_247": True,
        "value_score": _value_score(96, 80, 40, 82),
        "beds": _beds(total=1800, icu=140, free_gen_pct=0.08, free_icu_pct=0.06),
        "pricing": _base_pricing_govt(),
        "photo_url": None,
        "established_year": 1926,
        "description": "Historic municipal medical college and general hospital.",
    },
    {
        "id": "apollo-navi-mumbai",
        "name": "Apollo Hospitals, Navi Mumbai",
        "city": "Mumbai",
        "address": "Plot 13, Parsik Hill Road, Sector 23, CBD Belapur 400614",
        "tier": "private",
        "specialties": [
            "Cardiology", "Neurosurgery", "Orthopedics", "Gastroenterology",
        ],
        "accreditation": ["NABH", "JCI"],
        "rating": 4.2,
        "review_count": 2780,
        "latitude": 19.0273,
        "longitude": 73.0313,
        "phone": "+91-22-33503350",
        "emergency_247": True,
        "value_score": _value_score(74, 86, 76, 85),
        "beds": _beds(total=500, icu=90, free_gen_pct=0.28, free_icu_pct=0.20),
        "pricing": _base_pricing_private(),
        "photo_url": None,
        "established_year": 2009,
        "description": "Navi Mumbai flagship, corporate multi-specialty.",
    },
    # BENGALURU ----------------------------------------------------------------
    {
        "id": "manipal-bangalore",
        "name": "Manipal Hospital, Old Airport Road",
        "city": "Bengaluru",
        "address": "98, HAL Airport Road, Kodihalli, Bengaluru 560017",
        "tier": "premium",
        "specialties": [
            "Cardiology", "Oncology", "Neurology", "Nephrology", "Orthopedics",
        ],
        "accreditation": ["NABH", "JCI"],
        "rating": 4.3,
        "review_count": 5920,
        "latitude": 12.9601,
        "longitude": 77.6489,
        "phone": "+91-80-22221111",
        "emergency_247": True,
        "value_score": _value_score(64, 90, 76, 88),
        "beds": _beds(total=650, icu=120, free_gen_pct=0.24, free_icu_pct=0.18),
        "pricing": _base_pricing_premium(),
        "photo_url": None,
        "established_year": 1991,
        "description": "Manipal Hospitals flagship in Bengaluru.",
    },
    {
        "id": "fortis-bg-road",
        "name": "Fortis Hospital, Bannerghatta Road",
        "city": "Bengaluru",
        "address": "154/9, Bannerghatta Road, Opposite IIM, Bengaluru 560076",
        "tier": "private",
        "specialties": [
            "Cardiology", "Orthopedics", "Neurology", "Gastroenterology",
        ],
        "accreditation": ["NABH", "NABL"],
        "rating": 4.2,
        "review_count": 3480,
        "latitude": 12.8899,
        "longitude": 77.5972,
        "phone": "+91-80-66214444",
        "emergency_247": True,
        "value_score": _value_score(72, 85, 74, 84),
        "beds": _beds(total=402, icu=80, free_gen_pct=0.22, free_icu_pct=0.16),
        "pricing": _base_pricing_private(),
        "photo_url": None,
        "established_year": 2006,
        "description": "South Bengaluru multi-specialty hospital.",
    },
    {
        "id": "narayana-bangalore",
        "name": "Narayana Institute of Cardiac Sciences",
        "city": "Bengaluru",
        "address": "Bommasandra Industrial Area, Anekal Taluk, Bengaluru 560099",
        "tier": "private",
        "specialties": [
            "Cardiac Sciences", "Cardiac Surgery", "Nephrology", "Oncology",
        ],
        "accreditation": ["NABH", "JCI"],
        "rating": 4.5,
        "review_count": 4120,
        "latitude": 12.8100,
        "longitude": 77.6976,
        "phone": "+91-80-71222222",
        "emergency_247": True,
        "value_score": _value_score(80, 92, 74, 88),
        "beds": _beds(total=1000, icu=200, free_gen_pct=0.25, free_icu_pct=0.20),
        "pricing": _base_pricing_private(),
        "photo_url": None,
        "established_year": 2001,
        "description": "Narayana Health flagship \u2014 known for affordable cardiac care.",
    },
    {
        "id": "bmch-bangalore",
        "name": "Bangalore Medical College and Research Institute",
        "city": "Bengaluru",
        "address": "K R Road, Fort, Bengaluru 560002",
        "tier": "government",
        "specialties": [
            "General Medicine", "Trauma", "Obstetrics", "Pediatrics",
        ],
        "accreditation": ["NABH (Entry)"],
        "rating": 3.9,
        "review_count": 2140,
        "latitude": 12.9581,
        "longitude": 77.5730,
        "phone": "+91-80-26700810",
        "emergency_247": True,
        "value_score": _value_score(96, 78, 45, 80),
        "beds": _beds(total=1500, icu=90, free_gen_pct=0.12, free_icu_pct=0.10),
        "pricing": _base_pricing_govt(),
        "photo_url": None,
        "established_year": 1955,
        "description": "Government teaching hospital in central Bengaluru.",
    },
    # CHENNAI ------------------------------------------------------------------
    {
        "id": "apollo-chennai",
        "name": "Apollo Hospitals, Greams Road",
        "city": "Chennai",
        "address": "21, Greams Lane, Off Greams Road, Chennai 600006",
        "tier": "premium",
        "specialties": [
            "Cardiology", "Oncology", "Neurosurgery", "Transplant", "Robotic Surgery",
        ],
        "accreditation": ["NABH", "JCI"],
        "rating": 4.4,
        "review_count": 6840,
        "latitude": 13.0605,
        "longitude": 80.2494,
        "phone": "+91-44-28293333",
        "emergency_247": True,
        "value_score": _value_score(60, 92, 74, 90),
        "beds": _beds(total=560, icu=110, free_gen_pct=0.22, free_icu_pct=0.16),
        "pricing": _base_pricing_premium(),
        "photo_url": None,
        "established_year": 1983,
        "description": "First corporate hospital in India, quaternary tertiary care.",
    },
    {
        "id": "miot-chennai",
        "name": "MIOT International",
        "city": "Chennai",
        "address": "4/112, Mount Poonamallee Road, Manapakkam, Chennai 600089",
        "tier": "private",
        "specialties": [
            "Orthopedics", "Cardiology", "Nephrology", "Neurology",
        ],
        "accreditation": ["NABH", "NABL"],
        "rating": 4.3,
        "review_count": 3120,
        "latitude": 13.0217,
        "longitude": 80.1739,
        "phone": "+91-44-22492288",
        "emergency_247": True,
        "value_score": _value_score(72, 88, 76, 86),
        "beds": _beds(total=1000, icu=120, free_gen_pct=0.24, free_icu_pct=0.18),
        "pricing": _base_pricing_private(),
        "photo_url": None,
        "established_year": 1999,
        "description": "Chennai\u2019s ortho + multi-specialty landmark.",
    },
    {
        "id": "gh-chennai",
        "name": "Rajiv Gandhi Government General Hospital",
        "city": "Chennai",
        "address": "Park Town, Chennai 600003",
        "tier": "government",
        "specialties": [
            "General Medicine", "Trauma", "Cardiology", "Obstetrics", "Pediatrics",
        ],
        "accreditation": ["NABH (Entry)"],
        "rating": 4.0,
        "review_count": 4560,
        "latitude": 13.0817,
        "longitude": 80.2760,
        "phone": "+91-44-25305000",
        "emergency_247": True,
        "value_score": _value_score(96, 80, 42, 82),
        "beds": _beds(total=2900, icu=180, free_gen_pct=0.08, free_icu_pct=0.06),
        "pricing": _base_pricing_govt(),
        "photo_url": None,
        "established_year": 1664,
        "description": "One of India\u2019s oldest general hospitals.",
    },
    # HYDERABAD ---------------------------------------------------------------
    {
        "id": "apollo-hyd",
        "name": "Apollo Hospitals, Jubilee Hills",
        "city": "Hyderabad",
        "address": "Road No. 72, Film Nagar, Jubilee Hills, Hyderabad 500033",
        "tier": "premium",
        "specialties": [
            "Cardiology", "Oncology", "Neurosurgery", "Orthopedics", "Transplant",
        ],
        "accreditation": ["NABH", "JCI"],
        "rating": 4.4,
        "review_count": 5210,
        "latitude": 17.4114,
        "longitude": 78.4066,
        "phone": "+91-40-23607777",
        "emergency_247": True,
        "value_score": _value_score(60, 92, 76, 88),
        "beds": _beds(total=550, icu=110, free_gen_pct=0.24, free_icu_pct=0.18),
        "pricing": _base_pricing_premium(),
        "photo_url": None,
        "established_year": 1988,
        "description": "Jubilee Hills flagship, tertiary + quaternary care.",
    },
    {
        "id": "kims-hyd",
        "name": "KIMS Hospitals, Secunderabad",
        "city": "Hyderabad",
        "address": "1-8-31/1, Minister Road, Krishna Nagar, Secunderabad 500003",
        "tier": "private",
        "specialties": [
            "Cardiology", "Neurosurgery", "Nephrology", "Orthopedics",
        ],
        "accreditation": ["NABH", "NABL"],
        "rating": 4.2,
        "review_count": 3280,
        "latitude": 17.4413,
        "longitude": 78.4989,
        "phone": "+91-40-44885000",
        "emergency_247": True,
        "value_score": _value_score(74, 86, 72, 82),
        "beds": _beds(total=400, icu=70, free_gen_pct=0.20, free_icu_pct=0.16),
        "pricing": _base_pricing_private(),
        "photo_url": None,
        "established_year": 2004,
        "description": "Multi-specialty tertiary hospital in Secunderabad.",
    },
    {
        "id": "nims-hyd",
        "name": "Nizam\u2019s Institute of Medical Sciences (NIMS)",
        "city": "Hyderabad",
        "address": "Punjagutta, Hyderabad 500082",
        "tier": "government",
        "specialties": [
            "Cardiology", "Neurology", "Nephrology", "Oncology",
        ],
        "accreditation": ["NABH (Entry)"],
        "rating": 4.2,
        "review_count": 3980,
        "latitude": 17.4266,
        "longitude": 78.4482,
        "phone": "+91-40-23489000",
        "emergency_247": True,
        "value_score": _value_score(94, 85, 48, 84),
        "beds": _beds(total=1500, icu=140, free_gen_pct=0.12, free_icu_pct=0.10),
        "pricing": _base_pricing_govt(),
        "photo_url": None,
        "established_year": 1964,
        "description": "Autonomous government tertiary teaching hospital.",
    },
    # PUNE --------------------------------------------------------------------
    {
        "id": "ruby-hall-pune",
        "name": "Ruby Hall Clinic",
        "city": "Pune",
        "address": "40, Sassoon Road, Pune 411001",
        "tier": "private",
        "specialties": [
            "Cardiology", "Oncology", "Neurology", "Orthopedics", "Nephrology",
        ],
        "accreditation": ["NABH", "NABL"],
        "rating": 4.2,
        "review_count": 3120,
        "latitude": 18.5333,
        "longitude": 73.8797,
        "phone": "+91-20-66455555",
        "emergency_247": True,
        "value_score": _value_score(72, 86, 74, 82),
        "beds": _beds(total=550, icu=80, free_gen_pct=0.22, free_icu_pct=0.16),
        "pricing": _base_pricing_private(),
        "photo_url": None,
        "established_year": 1959,
        "description": "Historic Pune multi-specialty hospital.",
    },
    {
        "id": "jehangir-pune",
        "name": "Jehangir Hospital",
        "city": "Pune",
        "address": "32, Sassoon Road, Pune 411001",
        "tier": "private",
        "specialties": [
            "Cardiology", "Neurology", "Obstetrics", "Oncology", "Nephrology",
        ],
        "accreditation": ["NABH", "NABL"],
        "rating": 4.1,
        "review_count": 2380,
        "latitude": 18.5292,
        "longitude": 73.8790,
        "phone": "+91-20-66819999",
        "emergency_247": True,
        "value_score": _value_score(70, 84, 72, 80),
        "beds": _beds(total=350, icu=60, free_gen_pct=0.20, free_icu_pct=0.14),
        "pricing": _base_pricing_private(),
        "photo_url": None,
        "established_year": 1946,
        "description": "Trust-managed Pune multi-specialty tertiary hospital.",
    },
    {
        "id": "sassoon-pune",
        "name": "Sassoon General Hospital",
        "city": "Pune",
        "address": "Near Pune Railway Station, Pune 411001",
        "tier": "government",
        "specialties": [
            "General Medicine", "Trauma", "Obstetrics", "Pediatrics", "Orthopedics",
        ],
        "accreditation": ["NABH (Entry)"],
        "rating": 3.9,
        "review_count": 1980,
        "latitude": 18.5297,
        "longitude": 73.8752,
        "phone": "+91-20-26128000",
        "emergency_247": True,
        "value_score": _value_score(96, 78, 40, 80),
        "beds": _beds(total=1300, icu=90, free_gen_pct=0.10, free_icu_pct=0.08),
        "pricing": _base_pricing_govt(),
        "photo_url": None,
        "established_year": 1867,
        "description": "Government tertiary teaching hospital.",
    },
    # KOLKATA -----------------------------------------------------------------
    {
        "id": "amri-kolkata",
        "name": "AMRI Hospitals, Dhakuria",
        "city": "Kolkata",
        "address": "P-4 & 5, Gariahat Road (South), Dhakuria, Kolkata 700029",
        "tier": "private",
        "specialties": [
            "Cardiology", "Orthopedics", "Neurology", "Nephrology",
        ],
        "accreditation": ["NABH", "NABL"],
        "rating": 4.2,
        "review_count": 3480,
        "latitude": 22.5027,
        "longitude": 88.3639,
        "phone": "+91-33-66800000",
        "emergency_247": True,
        "value_score": _value_score(74, 84, 72, 80),
        "beds": _beds(total=420, icu=70, free_gen_pct=0.22, free_icu_pct=0.16),
        "pricing": _base_pricing_private(),
        "photo_url": None,
        "established_year": 1996,
        "description": "South Kolkata multi-specialty tertiary hospital.",
    },
    {
        "id": "apollo-kolkata",
        "name": "Apollo Gleneagles Hospital",
        "city": "Kolkata",
        "address": "58 Canal Circular Road, Kolkata 700054",
        "tier": "premium",
        "specialties": [
            "Cardiac Sciences", "Oncology", "Neurosciences", "Transplant",
        ],
        "accreditation": ["NABH", "JCI"],
        "rating": 4.3,
        "review_count": 3980,
        "latitude": 22.5804,
        "longitude": 88.4088,
        "phone": "+91-33-23203040",
        "emergency_247": True,
        "value_score": _value_score(60, 90, 74, 86),
        "beds": _beds(total=700, icu=110, free_gen_pct=0.22, free_icu_pct=0.16),
        "pricing": _base_pricing_premium(),
        "photo_url": None,
        "established_year": 2003,
        "description": "Eastern India\u2019s Apollo flagship, tertiary + quaternary.",
    },
    # AHMEDABAD ---------------------------------------------------------------
    {
        "id": "sterling-ahmedabad",
        "name": "Sterling Hospital",
        "city": "Ahmedabad",
        "address": "Sterling Hospital Road, Off Gurukul Road, Memnagar 380052",
        "tier": "private",
        "specialties": [
            "Cardiology", "Nephrology", "Oncology", "Orthopedics",
        ],
        "accreditation": ["NABH", "NABL"],
        "rating": 4.2,
        "review_count": 2680,
        "latitude": 23.0546,
        "longitude": 72.5312,
        "phone": "+91-79-40011111",
        "emergency_247": True,
        "value_score": _value_score(74, 84, 74, 80),
        "beds": _beds(total=350, icu=60, free_gen_pct=0.22, free_icu_pct=0.16),
        "pricing": _base_pricing_private(),
        "photo_url": None,
        "established_year": 2001,
        "description": "Ahmedabad multi-specialty tertiary hospital.",
    },
    {
        "id": "civil-ahmedabad",
        "name": "Civil Hospital, Ahmedabad",
        "city": "Ahmedabad",
        "address": "Asarwa, Ahmedabad 380016",
        "tier": "government",
        "specialties": [
            "General Medicine", "Trauma", "Cardiology", "Obstetrics", "Pediatrics",
        ],
        "accreditation": ["NABH (Entry)"],
        "rating": 4.0,
        "review_count": 2140,
        "latitude": 23.0616,
        "longitude": 72.6023,
        "phone": "+91-79-22683900",
        "emergency_247": True,
        "value_score": _value_score(96, 80, 42, 82),
        "beds": _beds(total=2600, icu=140, free_gen_pct=0.10, free_icu_pct=0.08),
        "pricing": _base_pricing_govt(),
        "photo_url": None,
        "established_year": 1858,
        "description": "One of the largest government hospitals in Asia.",
    },
    # JAIPUR ------------------------------------------------------------------
    {
        "id": "fortis-jaipur",
        "name": "Fortis Escorts Hospital, Jaipur",
        "city": "Jaipur",
        "address": "JLN Marg, Malviya Nagar, Jaipur 302017",
        "tier": "private",
        "specialties": [
            "Cardiology", "Neurology", "Orthopedics", "Gastroenterology",
        ],
        "accreditation": ["NABH", "NABL"],
        "rating": 4.3,
        "review_count": 2780,
        "latitude": 26.8646,
        "longitude": 75.8161,
        "phone": "+91-141-2547000",
        "emergency_247": True,
        "value_score": _value_score(74, 86, 76, 84),
        "beds": _beds(total=200, icu=40, free_gen_pct=0.24, free_icu_pct=0.18),
        "pricing": _base_pricing_private(),
        "photo_url": None,
        "established_year": 2009,
        "description": "Rajasthan\u2019s premier corporate multi-specialty hospital.",
    },
    {
        "id": "sms-jaipur",
        "name": "SMS Hospital, Jaipur",
        "city": "Jaipur",
        "address": "Sawai Ram Singh Rd, Jaipur 302004",
        "tier": "government",
        "specialties": [
            "General Medicine", "Trauma", "Cardiology", "Neurology", "Obstetrics",
        ],
        "accreditation": ["NABH (Entry)"],
        "rating": 4.1,
        "review_count": 3480,
        "latitude": 26.9070,
        "longitude": 75.8083,
        "phone": "+91-141-2560291",
        "emergency_247": True,
        "value_score": _value_score(96, 80, 44, 82),
        "beds": _beds(total=2000, icu=140, free_gen_pct=0.10, free_icu_pct=0.08),
        "pricing": _base_pricing_govt(),
        "photo_url": None,
        "established_year": 1959,
        "description": "Government tertiary teaching hospital in Jaipur.",
    },
    # LUCKNOW -----------------------------------------------------------------
    {
        "id": "sgpgi-lucknow",
        "name": "SGPGI, Lucknow",
        "city": "Lucknow",
        "address": "Raebareli Road, Lucknow 226014",
        "tier": "government",
        "specialties": [
            "Cardiology", "Nephrology", "Oncology", "Neurology", "Transplant",
        ],
        "accreditation": ["NABH (Entry)"],
        "rating": 4.4,
        "review_count": 3120,
        "latitude": 26.7444,
        "longitude": 80.9370,
        "phone": "+91-522-2494000",
        "emergency_247": True,
        "value_score": _value_score(94, 88, 52, 88),
        "beds": _beds(total=1250, icu=140, free_gen_pct=0.14, free_icu_pct=0.10),
        "pricing": _base_pricing_govt(),
        "photo_url": None,
        "established_year": 1983,
        "description": "Autonomous government super-specialty referral hospital.",
    },
    {
        "id": "medanta-lucknow",
        "name": "Medanta Hospital, Lucknow",
        "city": "Lucknow",
        "address": "Sector A, Pocket 1, Sushant Golf City, Lucknow 226030",
        "tier": "private",
        "specialties": [
            "Cardiac Sciences", "Neurosciences", "Orthopedics", "Oncology",
        ],
        "accreditation": ["NABH", "NABL"],
        "rating": 4.3,
        "review_count": 1980,
        "latitude": 26.7809,
        "longitude": 80.9985,
        "phone": "+91-522-4505050",
        "emergency_247": True,
        "value_score": _value_score(72, 88, 78, 84),
        "beds": _beds(total=800, icu=140, free_gen_pct=0.26, free_icu_pct=0.20),
        "pricing": _base_pricing_private(),
        "photo_url": None,
        "established_year": 2018,
        "description": "Medanta group\u2019s Lucknow flagship, tertiary care.",
    },
    # KOCHI -------------------------------------------------------------------
    {
        "id": "amrita-kochi",
        "name": "Amrita Institute of Medical Sciences",
        "city": "Kochi",
        "address": "AIMS Ponekkara P.O., Kochi 682041",
        "tier": "private",
        "specialties": [
            "Cardiology", "Oncology", "Neurology", "Nephrology", "Transplant",
        ],
        "accreditation": ["NABH", "JCI", "NABL"],
        "rating": 4.4,
        "review_count": 3620,
        "latitude": 10.0359,
        "longitude": 76.2896,
        "phone": "+91-484-2801234",
        "emergency_247": True,
        "value_score": _value_score(74, 90, 74, 88),
        "beds": _beds(total=1200, icu=180, free_gen_pct=0.22, free_icu_pct=0.16),
        "pricing": _base_pricing_private(),
        "photo_url": None,
        "established_year": 1998,
        "description": "Kerala\u2019s premier tertiary care and academic hospital.",
    },
]


async def seed_hospitals() -> int:
    """Upsert all hospitals; safe to run on every startup."""
    db = get_db()
    count = 0
    for h in HOSPITALS:
        await db.hospitals.update_one({"id": h["id"]}, {"$set": h}, upsert=True)
        count += 1
    logger.info("Seeded %s hospitals", count)
    return count
